version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: orsproject3-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pro3
      MYSQL_USER: ors
      MYSQL_PASSWORD: ors
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  webapp:
    build: .
    container_name: orsproject3-webapp
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mysql_data:
